version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "priority: p3 low"
      - "status: acknowledged"
      - "type: dependencies"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - "priority: p3 low"
      - "status: acknowledged"
      - "type: dependencies"
