name: Version Patcher
author: Lemon
description: Patches the versions on C# (csproj VS2017+), npm (package.json), Python (setup.py) and other files
branding:
  color: purple
  icon: edit-3

inputs:
  version:
    description: The version to apply
    required: true
  trim:
    description: If the v or V at the beginning of the version should be trimmed
    required: false
    default: "true"
  use-tag:
    description: If the tag should be used as the version number on Release
    required: false
    default: "false"
  csproj-files:
    description: The glob used to find csproj files
    required: false
  npm-files:
    description: The glob used to find package.json files
    required: false
  setuppy-files:
    description: The glob used to find setup.py files
    required: false
  pyproject-files:
    description: The glob used to find pyproject.toml files
    required: false
  initpy-files:
    description: The glob used to find __init__.py files
    required: false
  fxmanifest-files:
    description: The glob used to find fxmanifest.lua files
    required: false
  gemspec-files:
    description: The glob used to find .gemspec files
    required: false

outputs:
  version:
    description: The version used to patch the files

runs:
  using: node16
  main: dist/main.js
